# Generated by Django 3.2.18 on 2023-03-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBelonging',
            fields=[
                ('belonging', models.CharField(default='无', max_length=100, primary_key=True, serialize=False, verbose_name='商品所属')),
                ('img', models.FileField(default='imgs/my_gilr_0.jpg', upload_to='belonging_imgs', verbose_name='商品所属图')),
            ],
            options={
                'verbose_name': '1-商品所属大类别',
                'verbose_name_plural': '1-商品所属大类别',
            },
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('name', models.CharField(default='无', max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='具体类别')),
                ('img', models.FileField(default='imgs/my_gilr_0.jpg', upload_to='categories_imgs', verbose_name='类别图')),
            ],
            options={
                'verbose_name': '3-具体类别',
                'verbose_name_plural': '3-具体类别',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('CustomColor', models.CharField(default='无', max_length=100, primary_key=True, serialize=False, verbose_name='自定义颜色')),
            ],
            options={
                'verbose_name': '自定义颜色',
                'verbose_name_plural': '自定义颜色',
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('discount', models.FloatField(default=1.0, primary_key=True, serialize=False, verbose_name='自定义折扣')),
            ],
            options={
                'verbose_name': '自定义折扣',
                'verbose_name_plural': '自定义折扣',
            },
        ),
        migrations.CreateModel(
            name='ProductNo',
            fields=[
                ('product_no', models.CharField(default='无', max_length=100, primary_key=True, serialize=False, verbose_name='商品编号')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('img', models.FileField(default='imgs/my_gilr_0.jpg', upload_to='imgs', verbose_name='商品主图')),
                ('img2', models.FileField(default='imgs/my_gilr_0.jpg', upload_to='imgs', verbose_name='商品副图')),
                ('details', models.FileField(default='imgs/my_gilr_0.jpg', upload_to='details', verbose_name='商品介绍')),
                ('describe', models.CharField(default='无', max_length=100, verbose_name='商品描述')),
                ('standard_price', models.FloatField(default=0.0, verbose_name='标准价格')),
                ('sold', models.IntegerField(verbose_name='已售数量')),
                ('likes', models.IntegerField(verbose_name='收藏数量')),
                ('onsale', models.BooleanField(default=False, verbose_name='是否上架')),
                ('thisBelonging', models.ForeignKey(blank=True, default='无', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.productbelonging')),
                ('thisPercentage', models.ForeignKey(blank=True, default='无', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.productdiscount')),
            ],
            options={
                'verbose_name': '4-商品通用信息',
                'verbose_name_plural': '4-商品通用信息',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('customSize', models.CharField(default='无', max_length=100, primary_key=True, serialize=False, verbose_name='自定义尺寸')),
            ],
            options={
                'verbose_name': '自定义尺寸',
                'verbose_name_plural': '自定义尺寸',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('type', models.CharField(default='无', max_length=100, primary_key=True, serialize=False, verbose_name='商品类型')),
                ('img', models.FileField(default='imgs/my_gilr_0.jpg', upload_to='type_imgs', verbose_name='商品类型图')),
            ],
            options={
                'verbose_name': '2-商品种类',
                'verbose_name_plural': '2-商品种类',
            },
        ),
        migrations.CreateModel(
            name='ProductTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag1', models.CharField(choices=[('热卖', '热卖'), ('新品', '新品'), ('推荐', '推荐'), ('爆款', '爆款'), ('特价', '特价'), ('折扣', '折扣'), ('满减', '满减'), ('满赠', '满赠'), ('满折', '满折'), ('畅销', '畅销'), ('秒杀', '秒杀'), ('秒杀抢购', '秒杀抢购')], default='无', max_length=100, verbose_name='商品标签1')),
                ('tag2', models.CharField(choices=[('热卖', '热卖'), ('新品', '新品'), ('推荐', '推荐'), ('爆款', '爆款'), ('特价', '特价'), ('折扣', '折扣'), ('满减', '满减'), ('满赠', '满赠'), ('满折', '满折'), ('畅销', '畅销'), ('秒杀', '秒杀'), ('秒杀抢购', '秒杀抢购')], default='无', max_length=100, verbose_name='商品标签1')),
                ('tag3', models.CharField(choices=[('热卖', '热卖'), ('新品', '新品'), ('推荐', '推荐'), ('爆款', '爆款'), ('特价', '特价'), ('折扣', '折扣'), ('满减', '满减'), ('满赠', '满赠'), ('满折', '满折'), ('畅销', '畅销'), ('秒杀', '秒杀'), ('秒杀抢购', '秒杀抢购')], default='无', max_length=100, verbose_name='商品标签1')),
                ('tag4', models.CharField(choices=[('热卖', '热卖'), ('新品', '新品'), ('推荐', '推荐'), ('爆款', '爆款'), ('特价', '特价'), ('折扣', '折扣'), ('满减', '满减'), ('满赠', '满赠'), ('满折', '满折'), ('畅销', '畅销'), ('秒杀', '秒杀'), ('秒杀抢购', '秒杀抢购')], default='无', max_length=100, verbose_name='商品标签1')),
                ('product_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.productno', verbose_name='商品编号')),
            ],
            options={
                'verbose_name': '6-商品标签',
                'verbose_name_plural': '6-商品标签',
            },
        ),
        migrations.AddField(
            model_name='productno',
            name='thisType',
            field=models.ForeignKey(blank=True, default='无', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.producttype'),
        ),
        migrations.AddField(
            model_name='productno',
            name='this_specific_categories',
            field=models.ForeignKey(blank=True, default='无', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.productcategories'),
        ),
        migrations.CreateModel(
            name='ProductInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(choices=[('自定义颜色', '自定义颜色'), ('红色', '红色'), ('蓝色', '蓝色'), ('绿色', '绿色'), ('黄色', '黄色'), ('白色', '白色'), ('黑色', '黑色'), ('紫色', '紫色'), ('橙色', '橙色'), ('棕色', '棕色'), ('灰色', '灰色'), ('粉色', '粉色')], max_length=100, verbose_name='颜色')),
                ('size', models.CharField(choices=[('自定义尺寸', '自定义尺寸'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], max_length=100, verbose_name='尺寸')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('discount', models.FloatField(verbose_name='折后价格')),
                ('stock', models.IntegerField(verbose_name='存货数量')),
                ('created', models.DateField(auto_now_add=True, verbose_name='上架日期')),
                ('onsale', models.BooleanField(default=False, verbose_name='是否上架')),
                ('isDiscount', models.BooleanField(default=False, verbose_name='是否折扣')),
                ('isPercentage', models.BooleanField(default=False, verbose_name='是否百分比折扣')),
                ('custom_color', models.ForeignKey(blank=True, default='无', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.productcolor')),
                ('custom_size', models.ForeignKey(blank=True, default='无', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.productsize')),
                ('product_no', models.ForeignKey(blank=True, default='无', null=True, on_delete=django.db.models.deletion.CASCADE, to='Product.productno')),
            ],
            options={
                'verbose_name': '5-商品信息',
                'verbose_name_plural': '5-商品信息',
            },
        ),
        migrations.AddField(
            model_name='productcategories',
            name='thisType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.producttype', verbose_name='商品种类'),
        ),
    ]
