# Generated by Django 3.2.18 on 2023-03-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='购买数量')),
                ('name', models.CharField(max_length=100, verbose_name='商品名称')),
                ('price', models.FloatField(verbose_name='商品价格')),
                ('commodityInfos_id', models.CharField(max_length=32, verbose_name='商品ID')),
                ('user_id', models.CharField(max_length=32, verbose_name='用户名')),
                ('img', models.CharField(max_length=100, verbose_name='商品图片')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.CreateModel(
            name='OrderInfos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(verbose_name='订单总价')),
                ('productinfo_amounts', models.CharField(max_length=200, verbose_name='商品ID-数量')),
                ('created', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('user_id', models.CharField(max_length=32, verbose_name='用户名')),
                ('state', models.CharField(choices=[('待支付', '待支付'), ('已支付', '已支付'), ('发货中', '发货中'), ('已签收', '已签收'), ('退货中', '退货中')], default='已支付', max_length=20, verbose_name='订单状态')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='订单备注')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
    ]
